### ISSUE TITLE
Qwerty hotkey

### ISSUE THREAD

**Issue by AgentK9** [jackrosenthal/threelayout#14]
I don't know AHK, hence why I'm making an issue and not my own PR or script.
Anyway, I was curious if there was a hotkey or if you could add a hotkey that would toggle the qwerty layout. I'd really like to learn 3L, but I want other people to be able to use my computer if they need to. Does this already exist in the form of the double alt? Or does that only turn off the layout?

Btw, you can thank Sumner's appearance on the Tailosive Tech Podcast for me wanting to try this.

**Comment by jnunez101** [comment]
There is a hotkey with the AHK. It is as you said pressing both alts will switch you between qwerty and 3l. To use the AHK file you need a program called Auto Hot Key. When you install it you can drag the AHK file onto the shortcut to the program and it should go over to 3l. When you restart windows it will return to qwerty and you will need to do this again. For a permanent solution you can open Auto Hot Key and make and exe file out of the ahk and drop it into the startup folder. -3l user

**Comment by jackrosenthal** [comment]
Yes, the key to toggle the AHK script on/off is Left Alt + Right Alt (both alt keys at same time).

I will leave this issue open as I should document this better, thanks.

**Comment by AgentK9** [comment]
Cool, thanks. Yeah, at first glance it looked like the double-alt was only an off switch, and not an on/off switch.
