### ISSUE TITLE
Suspend for certain apps/games (Windows-ahk)

### ISSUE THREAD

**Issue by fohrums** [jackrosenthal/threelayout#22]
I've grown to love this keyboard layout and use it as much as possible. I do however struggle with toggling to use games. I would like to stick to games default mapping as much as possible so rebinding isn't a good work around.

I've come across a one-liner code for ahk, but I can't include other games or apps executables. This one-liner code doesn't even allow multiple instances of it to also include an additional executable for suspending the Three Layout Keyboard ahk script:

<pre>
#if (!WinActive("ahk_exe insertcrappygamehere.exe") && !WinActive("Suspend, On"))
</pre>

What are your recomendations for using your keyboard layout on Windows via Autohotkey script to suspend particular Applications & Games when it's in focus?

**Comment by jackrosenthal** [comment]
I use windows rarely enough so that LAlt+RAlt does not seem like a major inconvenience. If you have a better solution, feel free to submit a pull request.

**Comment by Unknow0059** [comment]
You can try toying around with the [Window Group feature](https://www.autohotkey.com/docs/misc/WinTitle.htm#ahk_group). It allows you to do something whenever a window within a group of windows is detected.

**Comment by Rojetto** [comment]
Our driver for the Neo layout has this feature and also supports `3l` now. You can find more information here: https://github.com/Rojetto/ReNeo

You can configure a blacklist based on the window title. If you then switch to a window that matches a blacklist entry, the driver will automatically disable itself.

**Comment by jackrosenthal** [comment]
Thanks, that ReNeo driver looks pretty cool!

I made a callout to it in https://github.com/jackrosenthal/threelayout/commit/6580145bcc940cf6ce56a31d6984f9859bdc16b5

Going to close this as users looking for these advanced customization options should try out ReNeo.
