### ISSUE TITLE
Modifier CUR Add Selection Hotkeys

### ISSUE THREAD

**Issue by fohrums** [jackrosenthal/threelayout#28]
I want to be able to include selection hotkeys to the threelayout keyboard layout for Windows via Autohotkey. I have tried to include it myself but unable to make use of `Send` to do anything besides single press hotkeys. This means that I am unable to make use of `Send` to make single character selection and/or word selection for the following keys:

[![final.jpg](https://i.postimg.cc/g0JSByPq/final.jpg)](https://postimg.cc/LJc3J15n)

In the example I made use of these hotkeys because for the modifier `CUR` it is not used; and therefore, vacant for me to make customizations to it *(orange is Select-word and yellow is Select-character).*

# SELECTION HOTKEYS

> The following hotkeys are the ones i've chosen to include selection hotkeys
> I will not explain how or why "SC035" is used as the "CUR" modifier key

* SC035 & SC02C::Send **{Select-wordleft}**
  + Maybe `{^+Left}`
* SC035 & SC02D::Send **{Select-characterleft}**
  + Maybe `+Left`
* SC035 & SC02E::Send **{Select-characterright}**
  + Maybe `+Right`
* SC035 & SC02F::Send **{Select-wordright}**
  + Maybe `{^+Right}`

## NOTE

* If all goes well I would like to include Selection Hotkey for Select-lineforward and Select-linebackward

**Comment by jackrosenthal** [comment]
PR #30 just landed which provides pretty similar functionality in the Windows version. Update if this does not provide what you are requesting?

**Comment by fohrums** [comment]
> ...Update if this does not provide what you are requesting?

I grabbed the latest `3l.ahk` and it works, thank you! This is even a better design. Literally a very healthy layout you got going on here. Major Applaud!
