### ISSUE TITLE
How to add Three Layout as a custom layout to Klavaro? +1

### ISSUE THREAD

**Issue by Unknow0059** [jackrosenthal/threelayout#32]
Title, though I have another question:

How should one adapt Three Layout to other non-engUS languages, if even possible? 

My native keyboard layout has two extra keys, and I'm on Windows. Like, do I just change the AHK script to include those keys somewhere?

**Comment by jackrosenthal** [comment]
Yep, if you have any useful adaptations, you are welcome to submit them here as a pull request.

In Klavaro, I believe you go to "custom", and it allows you to insert specific letters for each key.

**Comment by Unknow0059** [comment]
I see. Thanks. 
I looked for a custom option in Klavaro but didn't realize it was in the layout list.
