### ISSUE TITLE
"cur" key (AB10) not working as modifier

### ISSUE THREAD

**Issue by nobodyatandnothing** [jackrosenthal/threelayout#37]
"cur" key does nothing when i set 3l keyboard in gnome settings

**Comment by nobodyatandnothing** [comment]
i am closing this issue as the issue seems to be with gnome. (when setting layout with localectl "cur" modifier works in display manager, and when setting 5th level modifier in tweaks, specified key works as "cur")

**Comment by jackrosenthal** [comment]
Interesting. I know GNOME is a little weird about how it manages keyboard layouts. I think there's an option in there for "custom layout" which is how I've gotten it working in GNOME in the past.
