### ISSUE TITLE
control keys are too hard to reach

### ISSUE THREAD

**Issue by nobodyatandnothing** [jackrosenthal/threelayout#40]
can a key above Enter be used as control?

**Comment by jackrosenthal** [comment]
I could see one of the bracket keys being useful for this. Want to send a PR?

**Comment by jackrosenthal** [comment]
On the other hand, I do like the idea of keeping the (QWERTY) `~`, `-`, `+=`, `[{`, `]}`, and `\|` keys "reserved for user customizations". Any thoughts on this and just using `xmodmap` or similar tooling to bind the key to do what you want?

**Comment by nobodyatandnothing** [comment]
> On the other hand, I do like the idea of keeping the (QWERTY) `~`, `-`, `+=`, `[{`, `]}`, and `\|` keys "reserved for user customizations". Any thoughts on this and just using `xmodmap` or similar tooling to bind the key to do what you want?

yes, thats probably best
