### ISSUE TITLE
capital delta not working on linux (Shift+Sym+Cur+D) 

### ISSUE THREAD

**Issue by nobodyatandnothing** [jackrosenthal/threelayout#42]

**Comment by jackrosenthal** [comment]
It seems to work fine for me. (I get this letter `Δ`).

Might help explaining some more details here if you can? I.e., which distribution are you using, X or Wayland, which applications have you tried, etc.?

**Comment by nobodyatandnothing** [comment]
clear linux 35650
gnome 41.2 on x
does not work in any applications
here is my shift+sym, top to bottom, left to right:
```
οφυψζξκχωβ
ωθεαιδρτησ
,μ.Σ;γλπν
```
seems they all work.

here is my shift+sym+cur, top to bottom, left to right:
```
ΟΦΥΨΖΞΚΧΩΒ
ΩΘΕΑ??ΡΤΗΣ
,Μ.J??ΛΠΝ
```
i have replaced keys that do not print anything with question marks

**Comment by jackrosenthal** [comment]
Is it possible that it's a hardware issue with your keyboard's rollover? Perhaps you are pressing more keys than the scanning matrix can detect?


I suspect this because all the keys which don't produce a result are grouped together.

Do you have another keyboard to try?

**Comment by cboushehri** [comment]
I have the same issue on Arch Linux 5.16.15, with i3-wm 4.20.1-2 on X
Computer is a Dell Latitude E5450 using the built in keyboard.

**Comment by jackrosenthal** [comment]
Closing as this is a hardware/firmware issue with the keyboards themselves (they likely don't support n-key rollover).
