### ISSUE TITLE
letter layout

### ISSUE THREAD

**Issue by iandoug** [jackrosenthal/threelayout#6]
hi

Is that letter layout our own invention?

Okay, poked around, answer is yes. Do you perhaps have the KLA json?

Thanks, Ian

**Comment by jackrosenthal** [comment]
Yes (although there were plenty of ideas taken from other layouts: antibracket, Neo, Dvorak, ...)

I'm not familiar with what a KLA json is, mind explaining?

Jack

**Comment by jackrosenthal** [comment]
Just realized you probably meant "Keyboard Layout Analyzer". If that's the case, here ya go (it's _mostly_ complete).

[three.json.gz](https://github.com/jackrosenthal/threelayout/files/1502645/three.json.gz)

**Comment by iandoug** [comment]
Thanks :-)
